# Generated by Django 3.2.5 on 2021-12-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_interests',
            field=models.TextField(null=True),
        ),
    ]
